language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - 2.2.4
  - 2.3.0
script:
  - bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: G3iHhh7WZZ4dX7fBznUuj6hqwSjRa0nHwWenjtbhi7TB3NwQIB36JUN2WhpJH4ibbzsrJtTb/SxSUVXz1ziZTPyq+/QGIZqNWwtfk87boCAe++gLJFZHzbB9jreKEbV2gBuipo6bJhnC0DO8jWw8eH4x1jwPqhbAok3KQhGk4jjcsrwP8ncueA8SFo9wW/1yHdP90O0YjJbpwBhJtNyNrynsmAl72Z8csxFArLu/qPS68QV9hFX3qt/bSskuTFb9Up4nbo7bDEoKglrfys56QK+NU6DaRxqfGrdihHJqpMH+9Kh5A72aoWd4fEL0GC4NIUxFHrb741/lARAV6FyrFC8jS+TjXdHvyCV+UtBdiF4yUKcQueuhY6udvn4Iif1OGIoUhBU5bzt888IdOHW/IbkfO76bq2HObOJdrEZC+Ng8A/juKML3vVAc3nd/jVOH37HnJ+ISLdn2d7QIMBA9iGqv9d+wRUeW8qKzuPs+ie6jj0uE+qYMf7HNTLQ9k/xZGY2mZINZqQCVMBBZNYWOT65GgrJLybaXDpl/wf9EA+HaMHqF3YCydDzYLrK5evzZOlnRmvlsmaBec0pjAmnBl5wGgfwidE9eia+w74zNu14YyJMBge/hRdvVhNhfe2xw5LQrtX+bKs4k8uJO/Bm29I8qkjs+doU4omMX4u/kEy8=
  gem: faat
  on:
    repo: xo8bit/faat
    branch: master
branches:
  only:
  - master
addons:
  code_climate:
    repo_token: 42e8f1763d78539f2d85eb0b89bd78392de8407a8703634bc4ab44e38dde08ae
