language: ruby

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head

script:
  - bundle exec rake

deploy:
  provider: rubygems
  api_key: ENV['RUBYGEMS_API_KEY']
  on:
    branch: master

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: ENV['CODECLIMATE_REPO_TOKEN']